### ISSUE TITLE
app not rendering to index.html

### ISSUE THREAD

**Issue by rocketNeck** [learn-co-curriculum/react-rendering#9]
I could not see the working DOM elements when I opened index.html in the browser.

I had to run `npm i --save-dev react-test-renderer react-dom` and then `npm run bundle`. That fixed the issue. Then I could render a snapshot of the DOM tree in the browser. 

Seems there is a [depreciation](https://www.npmjs.com/package/react-addons-test-utils) in the react-addons-test-utils package.

Perhaps an update to the package.json is in order for this and some of the previous labs.

**Comment by Lukeghenco** [comment]
This has been resolved with latest commit. Thanks @rocketNeck .
